const DICTIONARY = [
['despite','несмотря на','/dɪˈspaɪt/','preposition','Despite the rain, we decided to go for a walk.','Everyday','Weak'],
['achieve','достигать','/əˈtʃiːv/','verb','Small steps can help you achieve a bigger goal.','Work','Learning'],
['approach','подход; приближаться','/əˈprəʊtʃ/','noun / verb','We need a different approach to this problem.','Work','Learning'],
['aware','осознающий; знающий','/əˈweə/','adjective','Are you aware of how much you have learned?','Everyday','Weak'],
['bound','связанный; обязанный','/baʊnd/','adjective','You are not bound by your past decisions.','Everyday','Learning'],
['curious','любопытный','/ˈkjʊəriəs/','adjective','She was curious about the way memory works.','Mind & life','Learning'],
['encounter','встретить; столкнуться','/ɪnˈkaʊntə/','verb','You may encounter familiar words in unexpected places.','Everyday','Learning'],
['familiar','знакомый','/fəˈmɪliə/','adjective','The little café looked strangely familiar.','Mind & life','Weak'],
['eventually','в конце концов','/ɪˈventʃuəli/','adverb','Eventually, the new city began to feel like home.','Everyday','Learning'],
['hesitate','колебаться; медлить','/ˈhezɪteɪt/','verb','Do not hesitate to ask a question.','Everyday','Weak'],
['notice','замечать','/ˈnəʊtɪs/','verb','You notice more when you slow down.','Mind & life','Learning'],
['pattern','закономерность; узор','/ˈpætən/','noun','The brain looks for a pattern in new information.','Mind & life','Learning'],
['recall','вспоминать','/rɪˈkɔːl/','verb','I could recall the place, but not its name.','Mind & life','Weak'],
['rather','скорее; довольно','/ˈrɑːðə/','adverb','I would rather take the quieter road.','Everyday','Learning'],
['remain','оставаться','/rɪˈmeɪn/','verb','Some questions remain unanswered.','Everyday','Learning'],
['reveal','раскрывать; показывать','/rɪˈviːl/','verb','A small detail can reveal a bigger story.','Mind & life','Weak'],
['beyond','за пределами','/bɪˈjɒnd/','preposition','There is a small garden beyond the wall.','Travel','Learning'],
['wonder','задаваться вопросом; удивляться','/ˈwʌndə/','verb','I wonder why that moment felt so familiar.','Mind & life','Learning'],
['effort','усилие','/ˈefət/','noun','Learning a language takes time and effort.','Work','Learned'],
['journey','путешествие','/ˈdʒɜːni/','noun','The journey was just as interesting as the destination.','Travel','Learned'],
['improve','улучшать','/ɪmˈpruːv/','verb','Reading a little every day can improve your vocabulary.','Everyday','Learned'],
['opportunity','возможность','/ˌɒpəˈtjuːnəti/','noun','Every conversation is an opportunity to learn.','Work','New'],
['thoughtful','вдумчивый; заботливый','/ˈθɔːtfəl/','adjective','It was a thoughtful answer to a difficult question.','Mind & life','New'],
['meaningful','значимый; осмысленный','/ˈmiːnɪŋfəl/','adjective','We had a meaningful conversation.','Mind & life','New'],
['reluctant','неохотный; не желающий','/rɪˈlʌktənt/','adjective','He was reluctant to admit his mistake.','Everyday','New'],
['overwhelmed','перегруженный; подавленный','/ˌəʊvəˈwelmd/','adjective','She felt overwhelmed by all the new information.','Mind & life','New'],
['resilient','стойкий; способный восстанавливаться','/rɪˈzɪliənt/','adjective','People can be more resilient than they expect.','Mind & life','New'],
['embrace','принимать; обнимать','/ɪmˈbreɪs/','verb','Learn to embrace a little uncertainty.','Mind & life','New'],
['serendipity','счастливая случайность','/ˌserənˈdɪpəti/','noun','Finding that book was pure serendipity.','Mind & life','New'],
['uncertainty','неопределённость','/ʌnˈsɜːtənti/','noun','A new beginning always brings some uncertainty.','Mind & life','New'],
['habit','привычка','/ˈhæbɪt/','noun','Reading before bed became a habit.','Everyday','New'],
['memory','память; воспоминание','/ˈmeməri/','noun','The smell brought back a happy memory.','Mind & life','New'],
['evidence','доказательства','/ˈevɪdəns/','noun','There is no clear evidence for that explanation.','Mind & life','New'],
['confidence','уверенность','/ˈkɒnfɪdəns/','noun','Practice helped her build confidence.','Work','New'],
['instead','вместо этого','/ɪnˈsted/','adverb','We stayed home and read a book instead.','Everyday','New'],
['quiet','тихий','/ˈkwaɪət/','adjective','We found a quiet place to talk.','Travel','New'],
['stumble','спотыкаться; наткнуться','/ˈstʌmbəl/','verb','You can stumble upon a wonderful place by chance.','Travel','New'],
['shift','сдвиг; менять','/ʃɪft/','noun / verb','A small shift in perspective can change everything.','Mind & life','New'],
['perspective','точка зрения','/pəˈspektɪv/','noun','Travel can offer a different perspective.','Travel','New'],
['wander','бродить','/ˈwɒndə/','verb','We like to wander through the old town.','Travel','New']
].map((a,i)=>({id:a[0],word:a[0],translation:a[1],ipa:a[2],pos:a[3],example:a[4],group:a[5],status:a[6],addedAt:i}));
const ARTICLES = {
'Mind & life': {title:'The psychology of déjà vu', eyebrow:'A curious kind of familiar', intro:'A new place. A familiar feeling. Why does your mind insist you have been here before?', paragraphs:[
'You walk into a café in a city you have never visited. A cup touches a table. Someone laughs near the window. For a second, everything feels familiar. You are aware that this moment is new, yet part of your mind seems to recall it. Then the feeling disappears, leaving you curious about what just happened.',
'We call this déjà vu, a French expression meaning “already seen.” It is not the same as remembering an event. When you remember your last birthday, you can usually recall people, places, and details. With déjà vu, there is a feeling of recognition without a clear memory to explain it. That gap is what makes the experience so strange.',
'One possible explanation begins with the way we recognise places. Your brain does not store every room like a photograph. It can also respond to the pattern of a space: a doorway on the left, a table in the centre, light falling through a window. You may encounter a new room with a layout like one you saw years ago. The old details remain out of reach, but the arrangement can still feel familiar.',
'Imagine that the café has the same layout as a waiting room you visited as a child. You might not notice the connection. Your brain may respond to the similarity before you can explain it. This approach does not explain every case, but it helps reveal how a feeling can arrive without a story attached to it.',
'Another idea concerns the difference between familiarity and detailed recall. These processes normally work together, but they may briefly disagree. A moment can seem known even when you cannot retrieve any evidence of having lived it before. Despite the strength of the feeling, feeling certain is not always the same as being correct.',
'It is tempting to search for an extraordinary explanation. Some people wonder whether a dream predicted the scene. Others are reluctant to accept that an ordinary memory process could create such an unusual sensation. Yet a powerful experience does not automatically require a mysterious cause. The useful question is what we can observe and test.',
'There is still uncertainty. Déjà vu happens quickly and is difficult to recreate on demand. Researchers cannot simply ask everyone in a study to have the experience at the same moment. Instead, they use carefully designed situations to explore recognition, similarity, and memory. Each experiment answers a small question rather than solving the whole puzzle.',
'The next time it happens, you do not need to hesitate or search for a hidden message. Notice the room, the light, and the shape of the scene. Eventually the feeling will pass. What remains is a small reminder that memory is an active process: your mind is always trying to connect a new moment to something it already knows.'
]},
'Travel':{title:'The art of getting a little lost',eyebrow:'Take the quieter road',intro:'What if the best part of a journey is the part you did not plan?',paragraphs:[
'On her first morning in Lisbon, Maya was reluctant to leave her carefully planned route. She had a list of cafés, a map, and just three days. She wanted to achieve something with every hour. Then her phone battery died, and her journey took a different direction.',
'At first, she felt overwhelmed. Nothing looked familiar. She began to hesitate at every crossing. Rather than trying to recall the entire map, she decided to find somewhere quiet and ask for directions. Beyond a busy square, she noticed a small bakery with an open door.',
'The owner did not speak much English, but he was curious about her visit. They managed a conversation with short sentences and a few gestures. He drew a route on the back of a receipt. Then he pointed to a garden that was not on her list. Maya decided to embrace the opportunity.',
'The garden was ordinary in the best possible way. There were old benches, a sleeping cat, and people reading under the trees. She began to notice details that a busy schedule would have hidden. A pattern of blue tiles. The sound of cups through an open window. For once, she did not feel bound to the next destination.',
'Travel often promises a new perspective, but we can carry our old habits into every new city. We rush, compare, and collect photographs. A different approach is to leave a little space for uncertainty. You might encounter a conversation or a place that no guide could have chosen for you.',
'This does not mean ignoring practical plans. Keep an address, know how to return, and remain aware of your surroundings. The idea is simply to leave one afternoon open. Wander down a safe side street. Follow your interest rather than a ranking.',
'Eventually, Maya found her hotel. Despite missing two famous sights, she remembered that morning more clearly than the rest of her trip. The most meaningful part was not a monument. It was the effort of a short conversation and the unexpected confidence it gave her.',
'You do not need to travel far to try this. Take a different route home. Visit a neighbourhood you usually pass. Let a small shift in your routine reveal something new. Sometimes a little serendipity begins with giving yourself permission to be curious.'
]},
'Work & ideas':{title:'Why small habits outlast big plans',eyebrow:'A little, more often',intro:'You do not need a perfect routine. You need a beginning you can repeat.',paragraphs:[
'On Sunday evening, a new plan can feel easy. You will read for an hour, learn thirty words, and finally organise your notes. By Tuesday, you feel overwhelmed. By Friday, you are reluctant to open the app. The problem may not be your effort. It may be the size of the beginning.',
'A useful approach is to make the first action small and clear. Instead of “improve my English,” try “review five words after breakfast.” A specific action gives you less to decide. You already know what to do and when to begin.',
'The point is not that five words will transform your life overnight. It is that a small habit can remain possible on an ordinary busy day. You do not need to wait for confidence or inspiration. You need an action that fits into the life you already have.',
'Notice the difference between a goal and a cue. A goal tells you what you hope to achieve. A cue reminds you to act. A cup of coffee can become a cue to open your vocabulary. A train journey can become an opportunity to read one short article.',
'Familiar routines can help, but repetition alone is not everything. It matters what you do with the words. Try to recall a meaning before you reveal it. Encounter the word in a new sentence. Be curious about why the writer chose it. These small decisions make practice more meaningful.',
'You will sometimes forget. Despite regular practice, a word that seemed easy yesterday may feel new today. Rather than treating that as failure, use it as information. You have found a word that needs another meeting. You are not bound to a perfect record.',
'Eventually, you may notice a pattern. Starting takes less negotiation. You hesitate less. A word appears in something you read, and you understand it without translating. Progress can be quiet before it becomes obvious.',
'Leave room for a difficult day. Reduce the action if necessary and return when you can. A resilient routine is one that can bend. Beyond the big plan is a simpler question: what is the smallest useful thing you can do today?'
]}
};
